site_name: napari-mm
site_description: Napari plugin to load and visualize 3D image time series created in Map Manager
site_author: Robert Cudmore

theme: readthedocs


repo_url: https://github.com/cudmore/napari-mm

pages:
- Home: index.md
